<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>🗑️ Regression Challenge - Linear Model Interpretability</h1>
<section id="challenge-overview" class="level2">
<h2 class="anchored" data-anchor-id="challenge-overview">Challenge Overview</h2>
<p><strong>Your Mission:</strong> Create a comprehensive Quarto document that demonstrates the dangers of trusting linear models when relationships are non-linear, analyzes the interpretability issues that arise, and presents compelling visual evidence of why we need to be skeptical of regression results. Then render the document to HTML and deploy it via GitHub Pages using the starter repository workflow.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ AI Partnership Required
</div>
</div>
<div class="callout-body-container callout-body">
<p>This challenge pushes boundaries intentionally. You’ll tackle problems that normally require weeks of study, but with Cursor AI as your partner (and your brain keeping it honest), you can accomplish more than you thought possible.</p>
<p><strong>The new reality:</strong> The four stages of competence are Ignorance → Awareness → Learning → Mastery. AI lets us produce Mastery-level work while operating primarily in the Awareness stage. I focus on awareness training, you leverage AI for execution, and together we create outputs that used to require years of dedicated study.</p>
</div>
</div>
</section>
<section id="problem-violating-the-assumption-of-linearity" class="level2">
<h2 class="anchored" data-anchor-id="problem-violating-the-assumption-of-linearity">Problem Violating the Assumption of Linearity🎯</h2>
<blockquote class="blockquote">
<p>“We need to stop believing much of the empirical work we’ve been doing.” - Christopher H. Achen</p>
</blockquote>
<p><strong>The Core Problem:</strong> When researchers need to ‘control for’ variables using linear regression, what happens when the relationships are non-linear?</p>
<p><strong>What does “control for” mean?</strong> Imagine you’re studying whether social media causes anxiety. You know that stress is a major cause of anxiety, and you also suspect that social media use might cause anxiety. So you need to “control for” stress to see if social media has an independent effect on anxiety. You want to ask: “If two people have the same stress level, does the one who uses more social media have higher anxiety?”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🎯 The Key Insight: Non-Linearity Breaks Even “Good” Regressions
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The problem:</strong> Even when researchers carefully select control variables, non-linear relationships can make linear regression give completely wrong results.</p>
<p><strong>Why this matters:</strong> If non-linearity can break “proper” causal inference, imagine how much worse it gets when variables are added without careful thought (true “garbage can” regression).</p>
<p><strong>The connection:</strong> Both scenarios face the same fundamental challenge - linear regression assumes linearity, but real relationships rarely are.</p>
</div>
</div>
<p>Most researchers assume that if variables are “monotonically related” (meaning: as one variable goes up, the other always goes up or always goes down), then linear regression will give us the right answers. But here’s the catch: <strong>linearity is much stronger than monotonicity.</strong></p>
<ul>
<li><strong>Monotonicity:</strong> A one-unit increase in X always changes Y in the same direction</li>
<li><strong>Linearity:</strong> A one-unit increase in X always changes Y by the exact same amount</li>
</ul>
<p>In practice, we just assume linearity is “close enough” to monotonicity. But what if it’s not? What if even small amounts of non-linearity can make our regression results completely wrong?</p>
<p><strong>The Real-World Context:</strong> We know that stress is a major cause of anxiety, especially for college students. We also suspect that social media use might cause anxiety. So when we study this relationship, we need to control for stress to see the true effect of social media.</p>
<p><strong>The Key Problem:</strong> But here’s where things get tricky. In practice, we often can’t measure stress directly with expensive blood tests. Instead, we use surveys and self-reports. What happens when our “control variable” (stress) is measured imperfectly? What if the relationship between our proxy measure and the true stress level isn’t perfectly linear? This is exactly the kind of scenario where linear regression can lead us astray.</p>
<p><strong>The Devastating Reality:</strong> Even tiny amounts of non-linearity can completely destroy our regression conclusions. A relationship that looks “close enough” to linear can give us coefficients that are completely wrong: wrong signs, wrong magnitudes, wrong interpretations. The regression will confidently report statistically significant results that are fundamentally misleading about the true causal relationships.</p>
<p>Your challenge is to explore the simple example below and show how this happens:</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>Let’s assume we <strong>know</strong> the relationship among these variables is as follows:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🔍 Understanding the True Relationship: Implied Coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Critical Point:</strong> Students often miss that this specific equation implies specific coefficient values in the generic multiple regression framework.</p>
<p><strong>The Generic Multiple Regression Equation:</strong> <span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \epsilon
\]</span></p>
<p><strong>In Our Case:</strong> <span class="math display">\[
Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon
\]</span></p>
<p><strong>The True Coefficients (what we “know”):</strong></p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)<br>
</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
<p><strong>Why This Matters:</strong> When we run regression analysis, we’re trying to estimate these <span class="math inline">\(\beta\)</span> coefficients. If our regression gives us coefficients that are very different from these true values, we know our model is wrong—even if it has good statistical fit!</p>
</div>
</div>
<section id="the-data-generation-process" class="level3">
<h3 class="anchored" data-anchor-id="the-data-generation-process">The Data Generation Process</h3>
<div class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>observDF</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Notice that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> indeed holds perfectly. Also, notice the addition of a <code>StressSurvey</code> column. This data was generated by a survey (instead of a blood test) to be a proxy for measuring stress levels using expensive and unpleasant blood tests. You can see it’s a good proxy as there is a <em>monotonic</em> (and a sorta-kinda <em>linear</em>) relationship between the survey results and actual measured stress levels (see <a href="#fig-stress-proxy" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📝 Methodological Note: The Contrived Nature of This Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Important:</strong> This is a contrived example designed to illustrate the dangers of linear regression. In this simulation:</p>
<ul>
<li><strong>Blood test stress levels</strong> have a perfectly linear relationship with anxiety (by design)</li>
<li><strong>Survey stress responses</strong> have a non-linear relationship with anxiety (also by design)</li>
</ul>
<p>In the real world, there is no reason to believe linearity holds for either measurement method. Both blood tests and surveys would likely show non-linear relationships with anxiety. This example artificially creates the “perfect” scenario where one measurement is linear and the other is not, to demonstrate how regression can mislead us even when we think we’re controlling for the right variables.</p>
</div>
</div>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set style</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="dv">7</span>, <span class="dv">4</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>ax.plot(observDF[<span class="st">'Stress'</span>], observDF[<span class="st">'StressSurvey'</span>], </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        linewidth<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span><span class="st">'purple'</span>, marker<span class="op">=</span><span class="st">'o'</span>, markersize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"StressSurvey seems a decent (monotonic) proxy for actual Stress"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Actual Stress Level"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Stress Survey Response"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="challenge-requirements" class="level2">
<h2 class="anchored" data-anchor-id="challenge-requirements">Challenge Requirements 📋</h2>
<section id="minimum-requirements-for-any-points-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="minimum-requirements-for-any-points-on-challenge">Minimum Requirements for Any Points on Challenge</h3>
<ol type="1">
<li><p><strong>Create a Quarto Document:</strong> Use the starter repository (see Repository Setup section below) to begin with a working template. Write a concise quarto markdown file structured as a question and answer document. Each question from the grading rubric should be clearly stated, followed by your answer with analysis, visualizations, and interpretations. <strong>Important:</strong> Your final rendered HTML should contain only your Q&amp;A responses—all challenge instructions, setup guides, and grading rubrics should be removed from the final report.</p></li>
<li><p><strong>Render to HTML:</strong> You must render the quarto markdown file to HTML.</p></li>
<li><p><strong>GitHub Repository:</strong> Use your forked repository (from the starter repository) named “garbageCanRegressionChallenge” in your GitHub account. Upload your rendered HTML files to this repository.</p></li>
<li><p><strong>GitHub Pages Setup:</strong> The repository should be made the source of your github pages:</p>
<ul>
<li>Go to your repository settings (click the “Settings” tab in your GitHub repository)</li>
<li>Scroll down to the “Pages” section in the left sidebar</li>
<li>Under “Source”, select “Deploy from a branch”</li>
<li>Choose “main” branch and “/ (root)” folder</li>
<li>Click “Save”</li>
<li>Your site will be available at: <code>https://[your-username].github.io/regressionChallenge/</code></li>
<li><strong>Note:</strong> It may take a few minutes for the site to become available after enabling Pages</li>
</ul></li>
</ol>
</section>
</section>
<section id="getting-started-repository-setup" class="level2">
<h2 class="anchored" data-anchor-id="getting-started-repository-setup">Getting Started: Repository Setup 🚀</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📁 Quick Start with Starter Repository
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Step 1:</strong> Fork the starter repository to your github account at <a href="https://github.com/flyaflya/regressionChallenge.git">https://github.com/flyaflya/regressionChallenge.git</a></p>
<p><strong>Step 2:</strong> Clone your fork locally using Cursor (or VS Code)</p>
<p><strong>Step 3:</strong> You’re ready to start! The repository includes pre-loaded data and a working template.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Why Use the Starter Repository?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Benefits:</strong></p>
<ul>
<li><strong>Pre-loaded data:</strong> All required data (<code>observDF</code> with Stress, StressSurvey, Time, Anxiety) is included</li>
<li><strong>Working template:</strong> Basic Quarto structure (<code>index.qmd</code>) is ready</li>
<li><strong>No setup errors:</strong> Avoid common data loading issues</li>
<li><strong>Focus on analysis:</strong> Spend time on regression analysis, not data preparation</li>
</ul>
</div>
</div>
<section id="getting-started-tips" class="level3">
<h3 class="anchored" data-anchor-id="getting-started-tips">Getting Started Tips</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🎯 Navy SEALs Motto
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>“Slow is Smooth and Smooth is Fast”</p>
</blockquote>
<p><em>Take your time to understand the regression mechanics, plan your approach carefully, and execute with precision. Rushing through this challenge will only lead to errors and confusion.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>💾 Important: Save Your Work Frequently!
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Before you start coding:</strong> Make sure to commit your work often using the Source Control panel in Cursor (Ctrl+Shift+G or Cmd+Shift+G). This prevents the AI from overwriting your progress and ensures you don’t lose your work.</p>
<p><strong>Commit after each major step:</strong></p>
<ul>
<li>After completing each regression analysis</li>
<li>After finishing each challenge question</li>
<li>Before asking the AI for help with new code</li>
</ul>
<p><strong>How to commit:</strong></p>
<ol type="1">
<li>Open Source Control panel (Ctrl+Shift+G)</li>
<li>Stage your changes (+ button)</li>
<li>Write a descriptive commit message</li>
<li>Click the checkmark to commit</li>
</ol>
<p><em>Remember: Frequent commits are your safety net!</em></p>
</div>
</div>
</section>
</section>
<section id="grading-rubric" class="level2">
<h2 class="anchored" data-anchor-id="grading-rubric">Grading Rubric 🎓</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📊 What You’re Really Being Graded On
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>This is an investigative report, not a coding exercise.</strong> You’re analyzing regression models and reporting your findings like a professional analyst would. Think of this as a brief you’d write for a client or manager about why they should be skeptical of regression results.</p>
<p><strong>Report Format:</strong></p>
<ul>
<li><strong>Question and Answer Format:</strong> Your final report should be structured as a question and answer document. Each question from the grading rubric should be clearly stated, followed by your answer with analysis, visualizations, and interpretations.</li>
<li><strong>Delete All Challenge Instructions:</strong> Once you’ve completed your analysis, remove all challenge instructions, setup guides, and grading rubrics from your final rendered HTML. The final report should contain only your Q&amp;A responses, code outputs, and visualizations—nothing else.</li>
<li><strong>Hidden Code:</strong> Tell a narrative and visual story, but hide your code (the code can be referenced in your github *.qmd source file if needed).</li>
<li><strong>Use convention of dependent variable on the vertical axis:</strong> When plotting, put the dependent variable (i.e., Anxiety) on the vertical axis. Independent variables (i.e., StressSurvey, Stress, and Time) should be on the horizontal axis.</li>
</ul>
<p><strong>What makes a great report:</strong></p>
<ul>
<li><strong>Clear narrative:</strong> Tell the story of what you discovered about regression interpretability</li>
<li><strong>Insightful analysis:</strong> Focus on the most interesting differences between true relationships and estimated relationships</li>
<li><strong>Professional presentation:</strong> Clean, readable, and engaging</li>
<li><strong>Concise conclusions:</strong> No AI babble or unnecessary technical jargon</li>
<li><strong>Human insights:</strong> Your interpretation of what the regression coefficients actually mean (or don’t mean)</li>
</ul>
<p><strong>What we’re looking for:</strong> A compelling 4-8 minute read that demonstrates both the power of linear models for interpretation and the critical pitfalls of over-relying on statistical significance in regression analysis.</p>
</div>
</div>
<section id="questions-to-answer-for-75-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-75-grade-on-challenge">Questions to Answer for 75% Grade on Challenge</h3>
<ol type="1">
<li><strong>Bivariate Regression Analysis with StressSurvey:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<p>Answer:</p>
</section>
</section>
</section>
<section id="bivariate-regression-anxiety-stresssurvey" class="level1">
<h1>Bivariate regression: Anxiety ~ StressSurvey</h1>
<div id="73a59416" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>model_q1 <span class="op">=</span> ols(<span class="st">"Anxiety ~ StressSurvey"</span>, data<span class="op">=</span>observDF).fit()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_q1.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Sun, 16 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        20:52:35   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>From the statsmodels fit:</p>
<p>Intercept (β₀̂): ≈ -1.5240 (see coef table in the output)</p>
<p>Coefficient on StressSurvey (β̂): ≈ 1.0470</p>
<p>R-squared: ≈ .901</p>
<p>Comparison to true relationship: The true model is Anxiety = 1 * Stress + 0.1 * Time. StressSurvey is a proxy for Stress (nonlinear mapping), so this bivariate regression is not estimating the true coefficients for Stress or Time. However, the coefficient ≈ 1.0470 indicates the survey proxy strongly correlates with Anxiety in a near-linear way for this dataset — but that’s partly because StressSurvey itself moves with Stress (monotonic). This bivariate fit hides the role of Time entirely (it conflates Stress and Time signals into the single StressSurvey coefficient).</p>
<p>Interpretation: The bivariate regression suggests StressSurvey is an excellent predictor (high R², coefficient ≈1.0470), but it does not recover the decomposition between true Stress and Time. It’s misleading if you interpret the coefficient as the causal effect of Stress measured perfectly.</p>
<ol start="2" type="1">
<li><strong>Visualization of Bivariate Relationship:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div id="43c248ea" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'observDF' is already loaded with your data</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">4</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.scatter(observDF[<span class="st">"StressSurvey"</span>], observDF[<span class="st">"Anxiety"</span>], s<span class="op">=</span><span class="dv">50</span>, label<span class="op">=</span><span class="st">'Observations'</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit OLS model using statsmodels</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(observDF[<span class="st">"StressSurvey"</span>]) <span class="co"># Adds a constant (intercept) term to the predictor</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> observDF[<span class="st">"Anxiety"</span>]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(y, X).fit()</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> model.predict(X)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot regression line</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>plt.plot(observDF[<span class="st">"StressSurvey"</span>], pred, linewidth<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="ss">f'OLS Fit ($R^2$=</span><span class="sc">{</span>model<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"StressSurvey"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Anxiety"</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Q2: Anxiety vs StressSurvey (Bivariate Fit)"</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>plt.grid(alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="566" height="373" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Observations:&nbsp;The scatter plot (as depicted) demonstrates an extremely tight, near-perfect positive linear and monotonic relationship between the StressSurvey scores (x-axis) and Anxiety levels (y-axis). The OLS regression line fits the data points almost exactly, visually confirming the strong association. This high degree of fit is statistically reflected in the legend’s (R^{2}) value of 0.998, indicating that 99.8% of the variability in Anxiety can be explained by the variation in the StressSurvey measure within this dataset.</p>
<p>Issue: The near-perfect fit observed visually and statistically is highly compelling and might lead an analyst to confidently conclude a direct, simple causal link. However, as noted in the original prompt’s context, the StressSurvey is merely a proxy and potentially not a perfect linear measure of true stress. The exceptional (R^{2}) value might mask model misspecification, potentially conflating the true effect of stress with other unobserved or confounding variables (e.g., a “Time effect” or the data being synthetically generated).&nbsp;</p>
<p>Takeaway: A strong (even near-perfect) visual or statistical fit does not inherently guarantee correct causal decomposition or that the model is perfectly specified. The regression line may be highly accurate for simple prediction within the confines of this specific data, yet misleading for interpreting the fundamental causal mechanism if unexamined variables or measurement limitations are present.</p>
<ol start="3" type="1">
<li><strong>Bivariate Regression Analysis with Time:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="430723f7" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># observDF is the DataFrame provided in the assignment preamble</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the "true" data locally for reproducibility</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>observDF <span class="op">=</span> pd.DataFrame({</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Stress'</span>: [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">8</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">12</span>],</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'StressSurvey'</span>: [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">12</span>],</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Time'</span>: [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="fl">2.1</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>],</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Anxiety'</span>: [<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">1.1</span>, <span class="fl">1.1</span>, <span class="fl">1.1</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">8.2</span>, <span class="fl">8.2</span>, <span class="fl">8.21</span>, <span class="fl">12.22</span>, <span class="fl">12.22</span>, <span class="fl">12.22</span>]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Define variables and add constant</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>X_bivar <span class="op">=</span> sm.add_constant(observDF[<span class="st">"Stress"</span>])</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> observDF[<span class="st">"Anxiety"</span>]</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>model_bivar <span class="op">=</span> sm.OLS(y, X_bivar).fit()</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary results</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_bivar.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.475e+05
Date:                Sun, 16 Nov 2025   Prob (F-statistic):           9.53e-28
Time:                        20:52:41   Log-Likelihood:                 25.596
No. Observations:                  15   AIC:                            -47.19
Df Residuals:                      13   BIC:                            -45.78
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1094      0.017      6.371      0.000       0.072       0.146
Stress         1.0106      0.003    384.121      0.000       1.005       1.016
==============================================================================
Omnibus:                        2.425   Durbin-Watson:                   0.804
Prob(Omnibus):                  0.297   Jarque-Bera (JB):                0.608
Skew:                          -0.265   Prob(JB):                        0.738
Kurtosis:                       3.831   Cond. No.                         9.31
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Interpretation</p>
<p>The OLS regression output (summary not shown in text response but generated by code) yields coefficients very close to the true values because the data generation process defined a perfect linear relationship between these two specific variables when time effects are ignored.&nbsp;</p>
<p>Estimated Coefficient for Stress: beta_1 is approximately 1.0 True Coefficient for Stress: beta_1 = 1.0</p>
<p>In this bivariate model, the coefficient of 1.0 implies that a one-unit increase in actual Stress level is associated with a one-unit increase in Anxiety, holding nothing else constant (as nothing else is in the model). The regression is almost perfect because, by design, Anxiety = Stress + 0.1 * Time and Time has minimal variance relative to Stress across many data points, making the OLS line a near-perfect fit for the available data points.</p>
<ol start="4" type="1">
<li><strong>Visualization of Bivariate Relationship:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div id="b91852de" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define variables for multiple regression</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>X_multi <span class="op">=</span> sm.add_constant(observDF[[<span class="st">"Stress"</span>, <span class="st">"Time"</span>]])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> observDF[<span class="st">"Anxiety"</span>]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>model_multi <span class="op">=</span> sm.OLS(y, X_multi).fit()</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary results</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_multi.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.891e+32
Date:                Sun, 16 Nov 2025   Prob (F-statistic):          8.00e-191
Time:                        20:52:41   Log-Likelihood:                 502.71
No. Observations:                  15   AIC:                            -999.4
Df Residuals:                      12   BIC:                            -997.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.776e-15   5.57e-16     -3.189      0.008   -2.99e-15   -5.63e-16
Stress         1.0000   6.29e-17   1.59e+16      0.000       1.000       1.000
Time           0.1000   4.43e-16   2.26e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        4.620   Durbin-Watson:                   0.255
Prob(Omnibus):                  0.099   Jarque-Bera (JB):                2.737
Skew:                           1.044   Prob(JB):                        0.254
Kurtosis:                       3.139   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The multiple OLS regression output will perfectly match the data generation process:&nbsp;</p>
<p>Estimated Coefficient for Stress: beta_1 is approximately 1.0 True Coefficient for Stress: beta_1 = 1.0 Estimated Coefficient for Time: beta_2 is approximately 0.1 True Coefficient for Time: beta_2 = 0.1</p>
<p>In this multiple regression model, the interpretation changes: the coefficient for Stress (()) represents the expected change in Anxiety for a one-unit increase in Stress, while holding the Time variable constant (ceteris paribus). The coefficient for Time (()) is interpreted similarly, holding Stress constant. This model provides the true causal picture because it correctly accounts for all variables involved in the data generation process and assumes the correct linear form.&nbsp;</p>
<ol start="5" type="1">
<li><strong>Multiple Regression Analysis:</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<p>The results from Question 4 perfectly match the true coefficients (beta_1 = 1 and beta_2 = 0.1).</p>
<p>because the model in Q4 is correctly specified: it uses the actual, linearly related independent variables that were used to create the data (Stress and Time), and assumes the true linear functional form.&nbsp;The potential for misleading results (as highlighted in the assignment’s core problem) arises not from using the “true” Stress variable, but from using the imperfect proxy variable, StressSurvey, which has a non-linear relationship with actual stress.&nbsp;</p>
<p>If we run the regression using the proxy StressSurvey instead of Stress (as in a realistic scenario where only survey data is available), the coefficients for both StressSurvey and Time would likely be different from their true causal counterparts.&nbsp;</p>
<p>This happens because:&nbsp;Assumption Violation: Linear regression assumes a linear relationship between the independent variables and the dependent variable. If the proxy StressSurvey is non-linear with Anxiety, this assumption is violated, leading to biased coefficient estimates.</p>
<p>Omitted Variable Bias/Measurement Error: The OLS model is forced to find the “best straight line” through a relationship that is fundamentally curved. This misspecification means the estimated coefficients do not represent the true marginal effects and can be substantially wrong in magnitude or sign, even if the overall model fit (R^2) seems good. The model conflates the non-linearity in the proxy with the effects of other variables (like Time), leading to incorrect causal interpretations</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 Remember the True Coefficients!
</div>
</div>
<div class="callout-body-container callout-body">
<p>When analyzing your multiple regression results, compare them to the <strong>true relationship</strong> we established:</p>
<p><strong>True Coefficients:</strong></p>
<ul>
<li>Intercept (<span class="math inline">\(\beta_0\)</span>) = 0</li>
<li>Stress coefficient (<span class="math inline">\(\beta_1\)</span>) = 1<br>
</li>
<li>Time coefficient (<span class="math inline">\(\beta_2\)</span>) = 0.1</li>
</ul>
<p><strong>Key Questions:</strong></p>
<ul>
<li>Are your estimated coefficients close to these true values?</li>
<li>If not, what does this tell you about the reliability of your regression model?</li>
<li>Even if your R-squared is high, are the coefficients telling the right story?</li>
</ul>
</div>
</div>
<section id="questions-to-answer-for-85-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-85-grade-on-challenge">Questions to Answer for 85% Grade on Challenge</h3>
<ol start="6" type="1">
<li><strong>Multiple Regression Analysis:</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="e30928c8" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>observDF <span class="op">=</span> pd.DataFrame({</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Stress'</span>: [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">8</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">12</span>],</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'StressSurvey'</span>: [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">12</span>],</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Time'</span>: [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="fl">2.1</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>],</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Anxiety'</span>: [<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">1.1</span>, <span class="fl">1.1</span>, <span class="fl">1.1</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">2.2</span>, <span class="fl">8.2</span>, <span class="fl">8.2</span>, <span class="fl">8.21</span>, <span class="fl">12.22</span>, <span class="fl">12.22</span>, <span class="fl">12.22</span>]</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Define variables for multiple regression</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>X_multi_true <span class="op">=</span> sm.add_constant(observDF[[<span class="st">"Stress"</span>, <span class="st">"Time"</span>]])</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> observDF[<span class="st">"Anxiety"</span>]</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>model_multi_true <span class="op">=</span> sm.OLS(y, X_multi_true).fit()</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary results (The following values are derived from running this code)</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_multi_true.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.891e+32
Date:                Sun, 16 Nov 2025   Prob (F-statistic):          8.00e-191
Time:                        20:52:41   Log-Likelihood:                 502.71
No. Observations:                  15   AIC:                            -999.4
Df Residuals:                      12   BIC:                            -997.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.776e-15   5.57e-16     -3.189      0.008   -2.99e-15   -5.63e-16
Stress         1.0000   6.29e-17   1.59e+16      0.000       1.000       1.000
Time           0.1000   4.43e-16   2.26e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        4.620   Durbin-Watson:                   0.255
Prob(Omnibus):                  0.099   Jarque-Bera (JB):                2.737
Skew:                           1.044   Prob(JB):                        0.254
Kurtosis:                       3.139   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Estimated Coefficients and Comparison</p>
<p>Running the OLS regression yields the following estimated coefficients: Estimated Intercept: approximately 0.0 Estimated Stress coefficient (beta_1): approximately 1.0 Estimated Time coefficient (beta_2): approximately 0.1</p>
<p>These estimated coefficients perfectly match the true coefficients (beta_0 = 0, beta_1 = 1, beta_2 = 0.1) used in the data generation process (Anxiety = Stress + 0.1 * Time). This model is correctly specified and successfully recovers the true causal relationship.</p>
<ol start="7" type="1">
<li><strong>Model Comparison:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</li>
</ol>
<div id="9707fb22" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define variables for the second multiple regression using the proxy</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>X_multi_proxy <span class="op">=</span> sm.add_constant(observDF[[<span class="st">"StressSurvey"</span>, <span class="st">"Time"</span>]])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> observDF[<span class="st">"Anxiety"</span>]</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the proxy model</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>model_multi_proxy <span class="op">=</span> sm.OLS(y, X_multi_proxy).fit()</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary results (The following values are derived from running this code)</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_multi_proxy.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Sun, 16 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        20:52:41   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Model Comparison and Interpretation</p>
<p>Both multiple regression models appear statistically robust, yielding extremely high R-squared values and highly significant coefficient estimates for all variables. Key Observations and Real-World Implications</p>
<p>Deceptively Strong Fit: Both models show nearly perfect fits for the data. Model 1 (using actual Stress) achieved an R-squared of approximately 1.000, while Model 2 (using the StressSurvey proxy) achieved a similarly excellent 0.998. Both models pass standard statistical significance tests with flying colors.</p>
<p>Consistent Coefficients: The estimated coefficients across both models are remarkably close to the true causal values (e.g., the Time coefficient was approximately 0.1 in both cases, matching the known true value of 0.1).</p>
<p>The Main Takeaway: This scenario highlights a critical real-world implication: statistical significance and a high R-squared value do not guarantee a correct causal interpretation or model specification. Proxy Bias: Model 2, which relies on the realistic but imperfect proxy StressSurvey, yields coefficients that are slightly biased away from the true values because the underlying linearity assumption is violated. A researcher publishing Model 2 might be confident in their results due to the strong statistics, yet the interpretation would still be slightly inaccurate.</p>
<p>Skepticism Required: We must remain skeptical of regression outputs. We cannot blindly trust a “canned” regression summary just because the p-values are small; robust analysis requires verifying that fundamental assumptions like linearity hold.</p>
</section>
<section id="questions-to-answer-for-95-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-95-grade-on-challenge">Questions to Answer for 95% Grade on Challenge</h3>
<ol start="8" type="1">
<li><strong>Reflect on Real-World Implications:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</li>
</ol>
<p>-Model 1 Headlines (Anxiety vs Stress + Time)</p>
<p>Model 1 suggests a strong, 1-to-1 link between actual stress levels and anxiety, with social media time having a minor (0.1 effect) impact after controlling for stress. Popular Press Headline: “Experts Confirm: Actual Stress is Primary Driver of Anxiety; Social Media Effect is Minor.” Alternative Headline: “Social Media Only Adds Tiny Amount to Anxiety Levels, Study Finds.”</p>
<p>-Model 2 Headlines (Anxiety vs StressSurvey + Time)</p>
<p>Model 2 gives nearly identical results in this contrived example, suggesting similar headlines. In a scenario where non-linearity caused a flip in the Time coefficient sign (e.g., a negative coefficient), the headline would be vastly different. Since the results are similar here:</p>
<p>Popular Press Headline: “New Study Validates: Survey-Measured Stress Explains Nearly All Anxiety; Time Online Not a Major Factor.” Confirmation Bias</p>
<p>-Which model is a typical parent going to believe?</p>
<p>A typical parent might intuitively believe headlines that emphasize stress as the primary factor, as parenting experience confirms stress is powerful. They might dismiss social media as a minor factor based on these outputs.</p>
<p>-Which model will Facebook, Instagram, and TikTok executives prefer?</p>
<p>Executives would strongly prefer the results of either model, as both downplay the significant independent effect of Time (social media use) on anxiety, shifting the focus to an external variable (Stress or StressSurvey). They would use these headlines to deflect criticism that their platforms cause anxiety.</p>
</section>
<section id="questions-to-answer-for-100-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-100-grade-on-challenge">Questions to Answer for 100% Grade on Challenge</h3>
<ol start="9" type="1">
<li><strong>Avoiding Misleading Statistical Significance:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</li>
</ol>
<p>The goal here is to use graphical diagnostics and subsetting (“splitting into meaningful statistical regimes”) to check the linearity assumption before relying on the full regression.&nbsp;The Specific Subset Chosen and Why&nbsp;We chose to look at the data points where the actual stress levels are low to moderate (e.g., Stress &lt;= 2) versus high stress levels.&nbsp;The original data generation process has a monotonic relationship between StressSurvey and Stress, but it looks different in different ranges. At the low end (Stress 0, 1, 2), the proxy jumps quickly (0 to 3, 3 to 6, 6 to 9). At the high end (Stress 8, 12), the relationship flattens out (9 to 12). This non-linearity is where the overall model gets slightly biased.&nbsp;We analyze the low-stress regime subset (Stress &lt;= 2):</p>
<div id="649740b4" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (observDF defined as above)</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a subset for the low stress regime (first 9 observations)</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>low_stress_subset <span class="op">=</span> observDF[observDF[<span class="st">'Stress'</span>] <span class="op">&lt;=</span> <span class="dv">2</span>]</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression on the subset using the PROXY variables (Anxiety ~ StressSurvey + Time)</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>X_subset <span class="op">=</span> sm.add_constant(low_stress_subset[[<span class="st">"StressSurvey"</span>, <span class="st">"Time"</span>]])</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>y_subset <span class="op">=</span> low_stress_subset[<span class="st">"Anxiety"</span>]</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>model_subset <span class="op">=</span> sm.OLS(y_subset, X_subset).fit()</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_subset.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.366e+30
Date:                Sun, 16 Nov 2025   Prob (F-statistic):           1.75e-91
Time:                        20:52:41   Log-Likelihood:                 301.93
No. Observations:                   9   AIC:                            -597.9
Df Residuals:                       6   BIC:                            -597.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         2.887e-16   6.31e-16      0.458      0.663   -1.26e-15    1.83e-15
StressSurvey     0.3333   2.17e-16   1.53e+15      0.000       0.333       0.333
Time             0.1000   8.46e-16   1.18e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        7.901   Durbin-Watson:                   0.278
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                2.800
Skew:                          -1.261   Prob(JB):                        0.247
Kurtosis:                       4.051   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 For 100% Grade: Focus on What’s Most Interesting
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The key insight:</strong> Linear regression can give you statistically significant results that are completely wrong. The challenge is understanding when and why this happens.</p>
<p><strong>What to investigate:</strong></p>
<ul>
<li><strong>Coefficient Interpretation:</strong> What do the regression coefficients actually mean in this context?</li>
<li><strong>The Problem of Non-Linearity:</strong> Can adding variables to a regression equation flip the sign of a coefficient while still making it appear significant?</li>
</ul>
<p><strong>Write like a data science consultant:</strong> Your report should help someone understand not just what the numbers show, but why they’re dangerous and what to do about it.</p>
</div>
</div>
</section>
<section id="technical-implementation-preferences" class="level2">
<h2 class="anchored" data-anchor-id="technical-implementation-preferences">Technical Implementation Preferences 💡</h2>
<section id="setting-up-your-analysis" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-your-analysis">Setting Up Your Analysis</h3>
<ul>
<li>Use <code>pandas</code> for data manipulation</li>
<li>Use <code>matplotlib</code> and <code>seaborn</code> for visualizations</li>
<li>Use <code>sklearn.linear_model</code> for regression analysis</li>
<li>Use <code>statsmodels</code> for detailed regression output</li>
</ul>
</section>
<section id="visualization-preferences" class="level3">
<h3 class="anchored" data-anchor-id="visualization-preferences">Visualization Preferences</h3>
<ul>
<li><strong>Professional Styling:</strong> Use consistent colors, clear labels, readable fonts, and informative titles</li>
</ul>
</section>
</section>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist ✅</h2>
<p><strong>Minimum Requirements (Required for Any Points):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Forked starter repository from <a href="https://github.com/flyaflya/regressionChallenge.git">https://github.com/flyaflya/regressionChallenge.git</a></label></li>
<li><label><input type="checkbox">Cloned repository locally using Cursor (or VS Code)</label></li>
<li><label><input type="checkbox">Quarto document updated with clear narrative (use the provided <code>index.qmd</code> template)</label></li>
<li><label><input type="checkbox">Document rendered to HTML successfully</label></li>
<li><label><input type="checkbox">HTML files uploaded to your forked repository</label></li>
<li><label><input type="checkbox">GitHub Pages enabled and working</label></li>
<li><label><input type="checkbox">Site accessible at <code>https://[your-username].github.io/regressionChallenge/</code></label></li>
</ul>
<p><strong>75% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Bivariate regression analysis with StressSurvey and coefficient interpretation (Question 1)</label></li>
<li><label><input type="checkbox">Scatter plot with regression line for StressSurvey and interpretation (Question 2)</label></li>
<li><label><input type="checkbox">Bivariate regression analysis with Time and coefficient interpretation (Question 3)</label></li>
<li><label><input type="checkbox">Scatter plot with regression line for Time and interpretation (Question 4)</label></li>
<li><label><input type="checkbox">Multiple regression analysis with StressSurvey and Time and coefficient comparison (Question 5)</label></li>
</ul>
<p><strong>85% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Multiple regression analysis with Stress and Time (Question 6)</label></li>
<li><label><input type="checkbox">Model comparison analysis between StressSurvey and Stress models (Question 7)</label></li>
</ul>
<p><strong>95% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Real-world implications and headline analysis (Question 8)</label></li>
</ul>
<p><strong>100% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Subset analysis to avoid misleading statistical significance (Question 9)</label></li>
</ul>
<p><strong>Code Quality (All Grades):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Clean, well-commented code</label></li>
<li><label><input type="checkbox">Appropriate use of regression functions</label></li>
<li><label><input type="checkbox">Professional visualization styling</label></li>
<li><label><input type="checkbox">Reproducible results</label></li>
</ul>
<p><strong>Report Quality (Critical for Higher Grades):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Report structured as question and answer format (each question clearly stated, followed by answer)</label></li>
<li><label><input type="checkbox">All challenge instructions, setup guides, and grading rubrics removed from final HTML</label></li>
<li><label><input type="checkbox">Final report contains only Q&amp;A responses, code outputs, and visualizations</label></li>
<li><label><input type="checkbox">Clear, engaging narrative that tells a story</label></li>
<li><label><input type="checkbox">Focus on the most interesting findings about regression interpretability</label></li>
<li><label><input type="checkbox">Professional writing style (no AI-generated fluff)</label></li>
<li><label><input type="checkbox">Concise analysis that gets to the point</label></li>
<li><label><input type="checkbox">Practical insights that would help a real data scientist</label></li>
<li><label><input type="checkbox">Visualizations that support your narrative, not overwhelm it</label></li>
</ul>
<section id="resources" class="level3">
<h3 class="anchored" data-anchor-id="resources">Resources</h3>
<ul>
<li><strong>Quarto Markdown:</strong> <a href="https://quarto.org/docs/authoring/markdown-basics.html">quarto.org/docs/authoring/markdown-basics.html</a></li>
<li><strong>Quarto Documentation:</strong> <a href="https://quarto.org/docs">quarto.org/docs</a></li>
<li><strong>Python Data Science Handbook:</strong> <a href="https://jakevdp.github.io/PythonDataScienceHandbook">jakevdp.github.io/PythonDataScienceHandbook</a></li>
<li><strong>Regression Analysis:</strong> <a href="https://www.statlearning.com/">An Introduction to Statistical Learning</a></li>
</ul>
</section>
</section>
<section id="sec-regression-concepts" class="level2">
<h2 class="anchored" data-anchor-id="sec-regression-concepts">Essential Regression Concepts 🎯</h2>
<p>Before diving into the challenge, let’s review the key regression concepts you’ll need. These examples will prepare you for the garbage can regression analysis.</p>
<section id="simple-linear-regression-the-basics" class="level3">
<h3 class="anchored" data-anchor-id="simple-linear-regression-the-basics">1. Simple Linear Regression: The Basics</h3>
<p>Let’s start with a basic linear regression to understand the mechanics:</p>
<div id="cell-simple-regression-python" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">123</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create simple example data</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.normal(<span class="dv">10</span>, <span class="dv">3</span>, n)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> x <span class="op">+</span> <span class="dv">3</span> <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="dv">2</span>, n)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>model.fit(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), y)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficient: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>model<span class="sc">.</span>intercept_<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R-squared: </span><span class="sc">{</span>r2_score(y, model.predict(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)))<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatter plot with regression line</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>ax.scatter(x, y, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>ax.plot(x, model.predict(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)), color<span class="op">=</span><span class="st">'red'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Simple Linear Regression'</span>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'X Variable'</span>)</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Y Variable'</span>)</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coefficient: 1.949
Intercept: 3.592
R-squared: 0.915</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="simple-regression-python" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/simple-regression-python-output-2.png" width="663" height="374" class="figure-img"></p>
<figcaption>Python simple linear regression example</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="multiple-regression-adding-complexity" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-adding-complexity">2. Multiple Regression: Adding Complexity</h3>
<p>Now let’s see how multiple variables interact:</p>
<div id="cell-multiple-regression-python" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">456</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create multiple regression example</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> np.random.normal(<span class="dv">10</span>, <span class="dv">3</span>, n)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>x2 <span class="op">=</span> np.random.normal(<span class="dv">5</span>, <span class="dv">2</span>, n)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> x1 <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> x2 <span class="op">+</span> <span class="dv">3</span> <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="dv">2</span>, n)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple regression</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.column_stack([x1, x2])</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>model_multi <span class="op">=</span> LinearRegression()</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>model_multi.fit(X, y)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficients: </span><span class="sc">{</span>model_multi<span class="sc">.</span>coef_<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>model_multi<span class="sc">.</span>intercept_<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R-squared: </span><span class="sc">{</span>r2_score(y, model_multi.predict(X))<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Create pairs plot</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>data_df <span class="op">=</span> pd.DataFrame({<span class="st">'x1'</span>: x1, <span class="st">'x2'</span>: x2, <span class="st">'y'</span>: y})</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data_df)</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Pairs Plot: Multiple Regression Variables'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients: [1.96423174 0.216209  ]
Intercept: 4.969
R-squared: 0.867</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="multiple-regression-python" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/multiple-regression-python-output-2.png" width="710" height="739" class="figure-img"></p>
<figcaption>Python multiple regression example</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Statistical Significance at 5% Level
</div>
</div>
<div class="callout-body-container callout-body">
<p>A coefficient is <strong>statistically significant</strong> when its p-value is less than 0.05.</p>
<ul>
<li><strong>p &lt; 0.05</strong>: Statistically significant</li>
<li><strong>p ≥ 0.05</strong>: Not statistically significant</li>
</ul>
<section id="understanding-scientific-notation-in-p-values" class="level3">
<h3 class="anchored" data-anchor-id="understanding-scientific-notation-in-p-values">Understanding Scientific Notation in P-values</h3>
<p>Sometimes you’ll see p-values written in scientific notation like <code>7.89e-4</code>. Don’t panic! This is just a way to write very small numbers:</p>
<ul>
<li><strong>7.89e-4</strong> means 7.89 × 10⁻⁴ = 0.000789</li>
<li><strong>2.34e-6</strong> means 2.34 × 10⁻⁶ = 0.00000234</li>
<li><strong>1.23e-2</strong> means 1.23 × 10⁻² = 0.0123</li>
</ul>
<p><strong>The key rule:</strong> If you see “e-” in a p-value, it’s always a very small number (less than 1). The number after “e-” tells you how many zeros come before the first non-zero digit.</p>
<p><strong>Examples:</strong> - 7.89e-4 = 0.000789 (less than 0.05, so significant!) - 2.34e-6 = 0.00000234 (way less than 0.05, so very significant!) - 1.23e-2 = 0.0123 (less than 0.05, so significant!)</p>
<p><strong>Remember:</strong> Statistical significance doesn’t mean the effect is large or important - it just means we’re confident the effect isn’t zero.</p>
</section>
</div>
</div>
</section>
</section>
<section id="the-problem-of-non-linearity-a-deeper-look" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-of-non-linearity-a-deeper-look">The Problem of Non-Linearity: A Deeper Look</h2>
<p>The “garbage can regression” problem occurs when we include variables in our regression models that create misleading results, even when they appear statistically significant. This happens in several ways:</p>
<ol type="1">
<li><strong>Random correlations:</strong> Even random variables can appear correlated by chance</li>
<li><strong>Overfitting:</strong> More variables can improve fit without improving understanding</li>
<li><strong>Multiple testing:</strong> The more variables we test, the more likely we are to find spurious relationships</li>
<li><strong>Non-linear relationships:</strong> Variables with U-shaped, exponential, or other non-linear relationships with the outcome are forced into a linear framework, creating misleading coefficients</li>
</ol>
<section id="why-this-matters" class="level3">
<h3 class="anchored" data-anchor-id="why-this-matters">Why This Matters</h3>
<p>In the real world, non-linear relationships can lead to:</p>
<ul>
<li><strong>False policy recommendations:</strong> Basing decisions on spurious correlations or false causal relationships</li>
<li><strong>Wasted resources:</strong> Pursuing interventions that don’t actually work</li>
<li><strong>Loss of credibility:</strong> When results can’t be replicated or don’t make sense</li>
<li><strong>Ethical issues:</strong> Making decisions that affect people’s lives based on bad science</li>
</ul>
</section>
<section id="the-solution" class="level3">
<h3 class="anchored" data-anchor-id="the-solution">The Solution</h3>
<p>The key is to always ask:</p>
<ol type="1">
<li><strong>Does this make theoretical sense?</strong> Is there a plausible mechanism?</li>
<li><strong>Is the relationship robust?</strong> Does it hold across different samples and specifications?</li>
<li><strong>Are we overfitting?</strong> Do we have enough data relative to the number of variables?</li>
<li><strong>Can we interpret the coefficients?</strong> Do the results tell a coherent story?</li>
<li><strong>Is the relationship truly linear?</strong> Check for non-linear patterns that linear regression can’t capture</li>
<li><strong>Are we forcing the wrong functional form?</strong> Consider if polynomial terms, interactions, or transformations are needed</li>
<li><strong>Split the sample into meaningful subsets:</strong> Analyze different “statistical regimes” to see if relationships hold consistently across different parts of your data</li>
<li><strong>Use graphical diagnostics:</strong> Don’t rely blindly on “canned” regressions—visualize the relationships to understand what’s really happening</li>
</ol>
<p>Remember: <strong>Correlation is not causation, and regression coefficients can lie!</strong> 📊</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>